// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/publish/publisher.go

// Package publish is a generated GoMock package.
package publish

import (
	data "gol/cmd/data"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Print mocks base method.
func (m *MockPublisher) Print(grid data.Grid, iteration uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", grid, iteration)
}

// Print indicates an expected call of Print.
func (mr *MockPublisherMockRecorder) Print(grid, iteration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockPublisher)(nil).Print), grid, iteration)
}
